services:
  db:
    image: gvenzl/oracle-free:23.5-slim
    environment:
      ORACLE_PASSWORD: testerdb
      APP_USER: apptester
      APP_USER_PASSWORD: apptesterpass
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "echo 'select 1 from dual;' | sqlplus -s apptester/apptesterpass@//localhost:1521/freepdb1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
  app:
    build:
      context: .
      dockerfile: Dockerfile.main
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
      - "8001:8001"
      - "3000:3000"
volumes:
  oracle-data: